apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cookbookbo-front
  name: cookbookbo-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookbookbo-front
  strategy: {}
  template:
    metadata:
      labels:
        app: cookbookbo-front
    spec:
      containers:
      - image: jevillanueva/cookbookbo-front:latest
        name: cookbookbo-front
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: cookbookbo-front
        resources: {}
status: {}
