apiVersion: v1
kind: Service
metadata:
  labels:
    app: cookbookbo-front
  name: cookbookbo-front
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cookbookbo-front
status:
  loadBalancer: {}
